### ISSUE TITLE
On Rails 4.2, authentication doesn't seem to take effect.

### ISSUE THREAD

**Issue by epugh** [sportngin/okcomputer#106]
I have basic auth enabled via my initializer `okcomputer.rb`:

```
puts "requite basic auth via #{Rails.application.secrets.active_resource_user_name}"
# doesn't appear to be working...
OkComputer.require_authentication(Rails.application.secrets.active_resource_user_name, Rails.application.secrets.active_resource_user_password)

```

I see the puts, but I don't get prompted for the basic auth when I got `/okcomputer`,  it just runs it.  Not a big deal.  I'm on Rails 4.2, is that getting long in the tooth these days?

**Comment by pbyrne** [comment]
Strange. It's working for me in a Rails 4.2 app.

Authentication can be skipped for particular checks by passing an options hash with an `:except` key to `require_authentication`. Is it possible `OkComputer.require_authentication` is getting called somewhere else and having that option passed to it?

If that's not it, authentication will only be required if both a username and password are provided. Could you add `Rails.application.secrets.active_resource_user_password` to your debugging output to verify that it has a value, too?
