### ISSUE TITLE
Check name missing when in CheckCollection

### ISSUE THREAD

**Issue by dlpierce** [sportngin/okcomputer#132]
When registering a Check to a CheckCollection using the register instance method, the Check's name does not get set as it does when using the Registry's register class method. This causes the output to look like:

> Standard Checks
>   : PASSED Application is running (0s)
>   : PASSED Schema version: 20161208191710 (0s)
>   : PASSED Ruby 2.3.4-p301 (0s)

and the JSON output to have only one messge:

> {"":{"message":"Ruby 2.3.4-p301","success":true,"time":5.672976840287447e-06}}

**Comment by anfleene** [comment]
Thanks for the issue!

Looks like we put This line: https://github.com/sportngin/okcomputer/blob/master/lib/ok_computer/registry.rb#L43

In Registry when we should have put it in this method:
https://github.com/sportngin/okcomputer/blob/master/lib/ok_computer/check_collection.rb#L70-L72

Want to make a PR?
