### ISSUE TITLE
Abnormal Memory Increase?

### ISSUE THREAD

**Issue by PikachuEXE** [sportngin/okcomputer#137]
We are monitoring memory usage with scoutapp for our rails app and we found the health check is causing some memory increase recently (see screenshots below)

### Our setup
```ruby
# routes.rb
mount OkComputer::Engine, at: "/health_check"
```

```ruby
# config/initializers/okcomputer.rb
require 'okcomputer'

OkComputer.mount_at = false
```

### Screenshots of memory usage
![okcompuer_memory_1](https://user-images.githubusercontent.com/1018543/27366089-821e2f70-5676-11e7-9327-75f8a282fe6d.png)
![okcompuer_memory_2](https://user-images.githubusercontent.com/1018543/27366090-821e8dd0-5676-11e7-816a-c4ce55aa5c6d.png)
![okcompuer_memory_3](https://user-images.githubusercontent.com/1018543/27366091-825df1c8-5676-11e7-8e2f-97a5f52c971a.png)
![okcompuer_memory_4](https://user-images.githubusercontent.com/1018543/27366092-825e4cea-5676-11e7-9579-8aed35678ddc.png)
![okcompuer_memory_5](https://user-images.githubusercontent.com/1018543/27366093-827fb8f8-5676-11e7-9970-617b997fa366.png)

**Comment by anfleene** [comment]
Can you do the same tests with a brand new rails app with nothing else in it? 900k allocations is a lot. Hard to be sure it's OkC without stripping rails down to nothing.

**Comment by PikachuEXE** [comment]
Let me check it again in a few days
Since all memory jump all reported after the app started less than a minute
It could be inaccurate result

**Comment by PikachuEXE** [comment]
The monitoring vendor thinks it's related to the request is handled right after app booting
So we are gonna just ignore it
