### ISSUE TITLE
Automatically adding json format to custom mount route

### ISSUE THREAD

**Issue by kevinmarx** [sportngin/okcomputer#144]
When mounting OkComputer on a custom route via the `mount_at` config it is not immediately obvious that you must provide the format route parameter such as `OkComputer.mount_at = 'healthcheck/status(.:format)'`.

In the documentation it states that for the default route:
> Checks are available as plain text (by default) or JSON by appending .json

I assumed that this would apply the formatters to the custom mount_at route, perhaps it is a misunderstanding on my part. I am opening this issue to suggest that `(.:format)` either be appended by default if not provided or to update the readme to be more clear. I'm happy to do either.

**Comment by pbyrne** [comment]
The `mount_at` option was intended to only be for the path portion of the URL, such that the format shouldn't be necessary when configuring it.

For example, when using `OkComputer.mount_at = "foo"`, you'd fetch `/foo` for the default check, `/foo/all` or `/foo/all.json` for everything, `/foo/name` or `/foo/name.json` for the check named `name`.
