### ISSUE TITLE
Support Rails 5.2 migrations check

### ISSUE THREAD

**Issue by rmm5t** [sportngin/okcomputer#146]
Rails 5.2 fails the migrations check

```
This version of ActiveRecord does not support checking whether migrations are pending
```

ActiveRecord 5.1 (and prior) checked like so:

```ruby
ActiveRecord::Migrator.needs_migration?
```

But ActiveRecord 5.2 needs to check like so:

```ruby
ActiveRecord::Base.connection.migration_context.needs_migration?
```

I'll try to find the time to get a backwards compatible PR out soon, but I wanted to open this up for discussion first.

**Comment by pbyrne** [comment]
Thanks for reporting this!
