### ISSUE TITLE
Incorrect error status?

### ISSUE THREAD

**Issue by yulgolem** [sportngin/okcomputer#162]
Hi.

As far as I can see from OkComputer::OkComputerController, status might be either `:ok`, or `:error`.
Well, suppose we've got an issue there, because in the current Rack::Utils there are no such a status like  "error" (https://github.com/rack/rack/blob/master/lib/rack/utils.rb#L504), and if page renders with such a symbolic status, Rack::Utils cannot get a code for that and drops `ArgumentError (Unrecognized status code :error)`.

Locally in my project I've just made a patch to rename this status to `internal_server_error`, because all my necessary check info is already in page body. Maybe we should do the same? Or just declare a usable list of symbolic error codes to pass them from the checks?

Ready to prepare a PR with renaming.

**Comment by pbyrne** [comment]
Looks like this was fixed in https://github.com/sportngin/okcomputer/pull/161.
