### ISSUE TITLE
Rescuing from invalid Faraday error

### ISSUE THREAD

**Issue by ekampp** [sportngin/okcomputer#163]
After updating to Neo4j 9.6.0, Neo4j core 9..0, and Faraday 1.0.1 I'm seeing a lot of errors related to [line 9 in the build-in neo4j check](https://github.com/sportngin/okcomputer/blob/master/lib/ok_computer/built_in_checks/neo4j_check.rb#L9).

Specifically the problem is that Faraday has changed the name of the errors from `Faraday::Error::ConnectionFailed` to `Faraday::ConnectionFailed`.

**Comment by anfleene** [comment]
Closed by #164
