### ISSUE TITLE
App Version Check

### ISSUE THREAD

**Issue by anfleene** [sportngin/okcomputer#48]
It would be nice to have a new built in check that tells you what version of the app you have deployed

**Comment by pbyrne** [comment]
Capistrano 3 now puts the current release version in a `REVISION` file in the app root. That seems a reasonable default location to read, with either the (relative) file path a configuration option, or maybe a configurable block to execute which would output the revision (e.g., in our Unicorn configuration, we parse the revision into an environment variable visible to the app).

**Comment by anfleene** [comment]
I like using the REVISION file. using an ENV variable is fine too. We could try those two things and then give up. a user could set it themselves in an initializer.
