### ISSUE TITLE
Missing requirement: responders

### ISSUE THREAD

**Issue by leifg** [sportngin/okcomputer#52]
I started using okcomputer for my rails app (Rails 4.2.0).

As Rails 4.2. doesn't ship with the responders gem it needs to be added to the Gemfile separately:

   gem "responders", "~> 2.0"
   gem "okcomputer" 

I don't know if it's possible to make it a requirement only for newer rails versions.

But anyway I think it should be part of the documentation

**Comment by pbyrne** [comment]
Thanks for the bug report!

I've rolled out a change to master which fixes this problem. I think I'll hold off on releasing a new point release until we've got https://github.com/sportngin/okcomputer/issues/53 sorted out, though.
