### ISSUE TITLE
Issue using CacheCheck

### ISSUE THREAD

**Issue by dwbutler** [sportngin/okcomputer#60]
Hi,

The `CacheCheck` looks great, but I can't use it out-of-the-box because of [this line](https://github.com/sportngin/okcomputer/blob/d60bdf0d1a48d25bd9be712d718eb9deb781f757/lib/ok_computer/built_in_checks/cache_check.rb#L17):

```ruby
host = stats.select{|k,v| k =~ Regexp.new(Socket.gethostname) }.values[0]
```
It took me a while to figure out what this is doing, but I managed to hypothesize that you are running a memcache node locally on each app server. This is different from what I'm used to: a memcache cluster living entirely separately from the app servers.

So this line will always fail if your memcache server is separate from your app server (or if `Socket.gethostname` reports something that doesn't match). Think Amazon Elasticache or Memcachier on Heroku.

I'm not sure what the best solution is, but I would be in favor of turning this into a more generic check for connectivity between app and the memcached server. Reporting RAM usage is kind of cool, but may not mean a whole lot since one expects memcached to fill up and start evicting things.

It might also make sense to rename this to `MemcachedCheck` to make it clear that it only works with memcached. A more generic check might just try reading/writing from the cache.

**Comment by pbyrne** [comment]
You're right. That check has some non-universal assumptions baked into it. I agree that your suggestion of simply writing to and reading from the Rails cache seems a simpler solution to the problem of verifying that your cache is set up and working.

I wish I hadn't cut v1.0 just yesterday, though. Changing the existing behavior would reasonably be considered a breaking change (in case anyone was depending on the behavior and especially the output of the existing check). This precludes renaming the existing check, too.

Instead, I think I'll make a new check, `GeneralCacheCheck`, which does what you suggest, which we can release as v1.1.0.
