### ISSUE TITLE
Configuration option to force SSL?

### ISSUE THREAD

**Issue by dwbutler** [sportngin/okcomputer#65]
I was planning to expose a health check protected by basic auth. Our application unfortunately does not force SSL. So if the health check is pinged over HTTP, the username and password will be sent in the clear over and over.

My thought was for `OkComputer` to expose a configuration option to force SSL. This in turn would call `force_ssl` on the `OkComputerController`.

Thoughts?

**Comment by anfleene** [comment]
I think that makes sense. `OkComputer.force_ssl = true` seems pretty reasonable.

**Comment by pbyrne** [comment]
One gotcha is that if you're using OkComputer as your load balancer health check (and your load balancer is terminating your SSL), then it will need to use HTTP to make the check. I think that something similar to `OkComputer.require_authentication`, to which we can pass an options hash would make the most sense, to allow certain checks over HTTP.

```ruby
OkComputer.force_ssl(except: %w(default somethingelse))
```

I keep flip-flopping between whether it's reasonable for authentication and SSL to share a whitelist. I suppose they probably shouldn't.

**Comment by dwbutler** [comment]
That makes sense. We're doing exactly this - performing health checks on the default endpoint over HTTP - but on the same machine using [Eye](https://github.com/kostya/eye).

So the `except` approach sounds perfect.

The more I think about it, you would clearly want to force ssl whenever you use basic auth. So sharing the `except` list might be reasonable.

Maybe it could be configured like `OkComputer.public_endpoints = %w(default foo)`, and anything not in that list would use basic auth (if configured) and force SSL (if `OkComputer.force_ssl = true`).

Alternatively it could be configured as a whitelist: `OkComputer.secure_endpoints = %w(database really_important_internal_service)`.

Personally, I've chosen to secure all endpoints except the default endpoint. Exceptions tend to leak sensitive information such as server names, connection strings, credentials, etc.

**Comment by anfleene** [comment]
I like the `OkComputer.public_endpoints` idea. I agree that we should be more secure by default. Then all other endpoints use the security options you have enabled(basic auth/force_ssl).

**Comment by anfleene** [comment]
Closing due to staleness
