### ISSUE TITLE
Database Check Exception on rails with ActiveRecord::QueryCache and/or Migration Pending active

### ISSUE THREAD

**Issue by williscool** [sportngin/okcomputer#75]
Just fyi for anyone else who might use this

Re: 
https://github.com/rails/rails/issues/22154
 
Also 
https://gitter.im/rails/rails?at=5636de078afec94a69a89a50

**Comment by anfleene** [comment]
Thanks for the report. I think the best thing we could do is allow disabling the database check. I'll add that to our list of ideas for 2.0.

**Comment by anfleene** [comment]
See issue #77 for more details.
