### ISSUE TITLE
Skip Database check.

### ISSUE THREAD

**Issue by selaromi** [sportngin/okcomputer#77]
Hello! Is it possible to skip the database check on '/all'? I'm not using database in a current project, only redis.

Thanks! Great gem

**Comment by selaromi** [comment]
Nevermind. I can just rename 'database' to redis check.

´´´
OkComputer::RedisCheck.new({
host:ENV['AUTH_REDIS_HOSTNAME'],port:ENV['AUTH_REDIS_PORT']})
´´´

**Comment by pbyrne** [comment]
:+1: We've documented [in the README](https://github.com/sportngin/okcomputer#if-not-using-activerecord) how to swap out the database check for one that makes sense in your project. I'll make an issue, though, about disabling the database check altogether.
