### ISSUE TITLE
Allow disabling a default check

### ISSUE THREAD

**Issue by pbyrne** [sportngin/okcomputer#78]
Per https://github.com/sportngin/okcomputer/issues/77, it'd be nice to be able to disable the default `database` check altogether, if wanted. Something like `OkComputer::Registry.register "database", nil` or `OkComputer::Registry.unregister "database"` could do the trick.

**Comment by anfleene** [comment]
I like unregister It could be useful if/when we get to check groups and start thinking about sharing them between projects unregistering might be important.

**Comment by anfleene** [comment]
Closing this since we added `deregister` awhile back and documented it.
