### ISSUE TITLE
Possible XSS vulnerability

### ISSUE THREAD

**Issue by n0nick** [sportngin/okcomputer#94]
When requesting a check that was not registered with OkComputer, `OkComputer::Registry` [raises an error](https://github.com/sportngin/okcomputer/blob/144a8cd20d3e7ba793cc6e0c536c7c9bce1282d6/lib/ok_computer/registry.rb#L15) saying `"No check registered with '#{check_name}'"`, which in turn gets rendered by the controller.

The `check_name` value _is not escaped_, so might include malicious contents, such as HTML, JS, or third-party code (PDF, Flash, etc), as part of a [Cross-site Scripting attack](https://www.owasp.org/index.php/Cross-site_Scripting_(XSS)).

Instead, you should probably either
- Always escape user input (requested check name) when echoing back to the client, or
- Avoid rendering the check name, replacing the error with a more generic "Check not found" message.

**Comment by pbyrne** [comment]
The risk seems pretty low since the attacker would be the only person who sees the response, but it wouldn't hurt to close it.

**Comment by anfleene** [comment]
@n0nick do you have an example? I feel like we rescue_action_from so the message is never displayed.

**Comment by anfleene** [comment]
Ah I guess if you let the message pass into your 404 page or it's json it will display the message. https://github.com/sportngin/okcomputer/blob/master/app/controllers/ok_computer/ok_computer_controller.rb#L12-L17

@n0nick Feel free to open a pull request to fix it.

**Comment by pbyrne** [comment]
> Feel free to open a pull request to fix it.

Too late. I just did: https://github.com/sportngin/okcomputer/pull/95.

**Comment by anfleene** [comment]
Thanks @pbyrne

**Comment by n0nick** [comment]
Thanks @pbyrne for beating me to it! :)

Re risk level - an attacker could force a user to access this page (i.e. send a link, use an <img> tag etc.) which would execute code on the user's behalf, exposing the user's session data etc.

**Comment by anfleene** [comment]
FWIW you should hide your health checks behind a security model.
