### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by pbyrne** [sportngin/okcomputer#97]
Based on [this attempt to run against Rails 5](https://travis-ci.org/sportngin/okcomputer/jobs/143924449), it looks like we have a bit of work ahead of us to get the gem to work with Rails 5.

The main trouble seems to be the following error showing up against a lot of tests:

```
Failure/Error: controller.class.skip_before_filter :authenticate

ArgumentError:
  Before process_action callback :authenticate has not been defined
```

**Comment by chrisarcand** [comment]
This is because in Rails 5 an exception is now raised if the callback isn't actually registered, [unless you specifically specify `raise: false`](https://github.com/rails/rails/blob/6dfab475ca230dfcad7a603483431c8e7a8f908e/activesupport/lib/active_support/callbacks.rb#L634)

**Comment by chrisarcand** [comment]
@pbyrne I've got a branch with tests passing for Rails 5, I'll wait to open a PR until I have all of the [many] annoying deprecations gone, first. ❤️

**Comment by pbyrne** [comment]
https://github.com/sportngin/okcomputer/issues/98 looks like another Rails 5 bug. I suspect this'll get discovered as a failing test as we work in _this_ issue, but am marking it here anyway so we don't lose track.
