### ISSUE TITLE
Root route not matching a check with Rails 5

### ISSUE THREAD

**Issue by ralovely** [sportngin/okcomputer#98]
Hi.

In the process of upgrading an app to Rails 5,
we noticed the root route health check returns a 404.

It seems the root route returns a `No matching check`.
`/default`, `/all`, and other checks pass:

```
$ curl localhost/okcomputer
No matching check

$ curl localhost/okcomputer/
No matching check

$ curl localhost/okcomputer/default
default: PASSED Application is running

$ curl localhost/okcomputer/all
default: PASSED Application is running
database: PASSED Schema version: 20160708002852
revision: PASSED Version: 89e03b2f82666d8a37f309b32528f101c9d614a0
ruby_version: PASSED Ruby 2.3.1-p112
```

Workaround is to call `/okcomputer/default` instead of `/okcomputer`

Also, thank you for this very handy gem 👍

**Comment by ralovely** [comment]
Might be interesting to note though: in the process of upgrading to Rails 5,
the OkComputer gem was also upgraded from 1.7.1 to 1.8.0.
Maybe the change doesn't come from the Rails side but from this upgrade.

**Comment by pbyrne** [comment]
This seems to be related to Rails 5, since running v1.8.0 with Rails v4.2.7 seems 👌 . We've got some more work to do to get this gem ready for Rails 5, so I'm making note of this bug on https://github.com/sportngin/okcomputer/issues/97.

**Comment by chrisarcand** [comment]
@pbyrne Interestingly enough, I found this is actually a regression in Rails 5.0: https://github.com/rails/rails/pull/25913
